services:
  - type: web
    name: signspeak-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --worker-class geventwebsocket.gunicorn.workers.GeventWebSocketWorker -w 1 app:app --bind 0.0.0.0:$PORT --timeout 120
    rootDir: backend
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
