services:
  - type: web
    name: sign-language-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --worker-class gevent -w 1 app:app --bind 0.0.0.0:$PORT
    rootDir: backend
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
